export const projects = [
  {
    id: 1,
    name: "Nómadas",
    client: "Nómadas Design",
    category: "SaaS para Sublimación",
    type: "Plataforma especializada de diseño",
    website: "https://nomadas.design/home",
    year: 2024,
    status: "En producción",
    role: "Desarrollo de sistema especializado y visualización 3D",
    image: "/mockup-nomadas.png",
    description:
      "Nómadas es una empresa especializada en la creación de diseños para sublimación en polos, poleras, camisetas, tazas y otros productos personalizados. En Kedevs desarrollamos un sistema especializado que permite modelar los diseños en 3D, facilitando la visualización realista del resultado final antes de la impresión.",
    features: [
      "Modelado de diseños en 3D",
      "Generación de semitonos",
      "Eliminación automática de fondos",
      "Eliminación de semitransparencias",
      "Optimización de archivos para impresión",
      "Herramientas avanzadas para profesionales de la sublimación",
    ],
    techStack: ["Next.js", "Three.js", "Node.js", "Procesamiento de imágenes"],
    gallery: ["/nomadas-1.png", "/nomadas-2.png", "/nomadas-3.png"],
    mockup: "/nomadas-mockup-1.png",
    cta: "Ver Proyecto",
  },

  {
    id: 2,
    name: "Hotel Jara",
    client: "Hotel Jara Huánuco",
    category: "SaaS para Hoteles",
    type: "Sistema de gestión interna",
    website: "https://hoteljarahuanuco.com/",
    year: 2023,
    status: "En producción",
    role: "Desarrollo de sistema integral de gestión hotelera",
    image: "/mockup-hotel-jara.png",
    description:
      "Hotel Jara es uno de los hoteles más importantes de la ciudad de Huánuco. En Kedevs desarrollamos un sistema integral de gestión interna diseñado para optimizar la operación diaria del hotel y centralizar todos sus procesos clave en una sola plataforma.",
    features: [
      "Módulos de check-in y check-out",
      "Sistema de reservas y cobros de habitaciones",
      "Control de habitaciones y mantenimiento",
      "Sistema de caja con ingresos diarios",
      "Integración con página web del hotel",
    ],
    techStack: [
      "Next.js",
      "Node.js",
      "PostgreSQL",
      "Dashboards administrativos",
    ],
    gallery: ["/jara-1.png", "/jara-2.png", "/jara-3.png"],
    mockup: "/jara-mockup-1.png",
    cta: "Ver Sistema",
  },

  {
    id: 3,
    name: "RSAVAPERU",
    client: "RSAVAPERU",
    category: "SaaS de Comercio Mayorista",
    type: "Ecommerce + sistema de gestión interna",
    website: "https://rsavaperu.com/",
    year: 2024,
    status: "En producción",
    role: "Desarrollo de ecommerce y sistema de gestión empresarial",
    image: "/mockup-rsavaperu.png",
    description:
      "RSAVAPERU es una empresa dedicada a la venta de ropa al por mayor, enfocada en abastecer a pequeños emprendedores y negocios emergentes. En Kedevs desarrollamos una solución digital integral que combina un ecommerce con un sistema de gestión interna.",
    features: [
      "Ecommerce para venta al por mayor",
      "Control de stock en tiempo real",
      "Gestión de compras y ventas",
      "Registro de proveedores",
      "Control de pagos a empleados y gastos",
      "Registro de productos mediante pistola lectora",
    ],
    techStack: [
      "Next.js",
      "Node.js",
      "PostgreSQL",
      "Lectores de código de barras",
    ],
    gallery: ["/rsavaperu-1.png", "/rsavaperu-2.png", "/rsavaperu-3.png"],
    mockup: "/rsavaperu-mockup-1.png",
    cta: "Visitar Tienda",
  },

  // {
  //   id: 4,
  //   name: "KedevsHome",
  //   client: "Kedevs",
  //   category: "SaaS de Gestión de Alquileres",
  //   type: "Plataforma SaaS",
  //   website: "https://kedevshome.site/",
  //   year: 2025,
  //   status: "SaaS activo",
  //   role: "Diseño y desarrollo completo de plataforma SaaS",
  //   image: "/nomadas-project-fondo-white.png",
  //   description:
  //     "KedevsHome es una plataforma SaaS desarrollada por Kedevs, enfocada en la gestión de alquileres de habitaciones y propiedades, pensada para propietarios que buscan orden, control y automatización en su negocio.",
  //   features: [
  //     "Gestión de habitaciones y tipos de habitaciones",
  //     "Registro y administración de inquilinos",
  //     "Configuración de servicios adicionales",
  //     "Control de pagos y fechas de vencimiento",
  //     "Notificaciones automáticas por correo electrónico",
  //     "Dashboard con métricas clave",
  //   ],
  //   techStack: [
  //     "Next.js",
  //     "Node.js",
  //     "PostgreSQL",
  //     "Automatización de correos",
  //   ],
  //   gallery: [
  //     "/projects/kedevshome/gallery-1.png",
  //     "/projects/kedevshome/gallery-2.png",
  //     "/projects/kedevshome/gallery-3.png",
  //   ],
  //   mockups: [
  //     "/projects/kedevshome/mockup-1.png",
  //     "/projects/kedevshome/mockup-2.png",
  //     "/projects/kedevshome/mockup-3.png",
  //   ],
  //   cta: "Explorar Plataforma",
  // },
];
