export const projects = [
  {
    id: 1,
    name: "Nómadas",
    client: "Nómadas Design",
    category: "Empresa de sublimación",
    type: "Control de pedidos y herramientas para diseñadores",
    website: "https://nomadas.design/home",
    year: 2024,
    status: "En producción",
    role: "Ordenar y automatizar la operación de diseño y pedidos",
    image: "/mockup-nomadas.png",
    description:
      "Nómadas manejaba sus pedidos por Telegram y controlaba clientes en hojas de cálculo. El negocio crecía pero las operaciones estaban desorganizadas. En Kedevs ordenamos sus procesos: centralizamos la gestión de clientes, automatizamos notificaciones y dimos herramientas a los diseñadores para trabajar con orden.",
    features: [
      "Control centralizado de clientes y pedidos",
      "Automatización de notificaciones a clientes",
      "Herramientas especializadas para diseñadores",
      "Visualización del producto antes de producción",
      "Eliminación de procesos manuales en el flujo de trabajo",
      "Operaciones organizadas desde un solo lugar",
    ],
    techStack: ["Next.js", "Three.js", "Node.js", "Procesamiento de imágenes"],
    gallery: ["/nomadas-1.png", "/nomadas-2.png", "/nomadas-3.png"],
    mockup: "/nomadas-mockup-1.png",
    cta: "Ver Proyecto",
  },

  {
    id: 2,
    name: "Hotel Jara",
    client: "Hotel Jara Huánuco",
    category: "Empresa de hotelería",
    type: "Control de operaciones y pagos",
    website: "https://hoteljarahuanuco.com/",
    year: 2023,
    status: "En producción",
    role: "Ordenar las operaciones diarias y el control de pagos del hotel",
    image: "/mockup-hotel-jara.png",
    description:
      "Hotel Jara operaba con registros manuales y control de pagos desordenado. Perdían reservas y tenían errores frecuentes en los cobros. En Kedevs centralizamos todas sus operaciones: control de habitaciones, reservas, cobros e ingresos diarios en una sola plataforma.",
    features: [
      "Control centralizado de reservas y habitaciones",
      "Gestión ordenada de cobros y caja diaria",
      "Control de mantenimiento y estado de habitaciones",
      "Seguimiento de ingresos en tiempo real",
      "Operaciones del hotel desde un solo lugar",
    ],
    techStack: [
      "Next.js",
      "Node.js",
      "PostgreSQL",
      "Dashboards administrativos",
    ],
    gallery: ["/jara-1.png", "/jara-2.png", "/jara-3.png"],
    mockup: "/jara-mockup-1.png",
    cta: "Ver Sistema",
  },

  {
    id: 3,
    name: "RSAVAPERU",
    client: "RSAVAPERU",
    category: "Empresa de comercio mayorista",
    type: "Control de ventas, stock y operaciones internas",
    website: "https://rsavaperu.com/",
    year: 2024,
    status: "En producción",
    role: "Ordenar las operaciones de venta, stock y pagos del negocio",
    image: "/mockup-rsavaperu.png",
    description:
      "RSAVAPERU manejaba su inventario y pagos manualmente. Con el crecimiento del negocio, los errores en stock y cobros aumentaban. En Kedevs ordenamos sus operaciones: control de inventario en tiempo real, gestión de ventas, seguimiento de pagos a empleados y centralización de toda la información del negocio.",
    features: [
      "Control de stock e inventario en tiempo real",
      "Gestión ordenada de ventas y compras",
      "Control de pagos a empleados y gastos",
      "Registro de proveedores centralizado",
      "Canal de ventas para clientes mayoristas",
      "Operaciones del negocio desde un solo lugar",
    ],
    techStack: [
      "Next.js",
      "Node.js",
      "PostgreSQL",
      "Lectores de código de barras",
    ],
    gallery: ["/rsavaperu-1.png", "/rsavaperu-2.png", "/rsavaperu-3.png"],
    mockup: "/rsavaperu-mockup-1.png",
    cta: "Visitar Tienda",
  },

  // {
  //   id: 4,
  //   name: "KedevsHome",
  //   client: "Kedevs",
  //   category: "SaaS de Gestión de Alquileres",
  //   type: "Plataforma SaaS",
  //   website: "https://kedevshome.site/",
  //   year: 2025,
  //   status: "SaaS activo",
  //   role: "Diseño y desarrollo completo de plataforma SaaS",
  //   image: "/nomadas-project-fondo-white.png",
  //   description:
  //     "KedevsHome es una plataforma SaaS desarrollada por Kedevs, enfocada en la gestión de alquileres de habitaciones y propiedades, pensada para propietarios que buscan orden, control y automatización en su negocio.",
  //   features: [
  //     "Gestión de habitaciones y tipos de habitaciones",
  //     "Registro y administración de inquilinos",
  //     "Configuración de servicios adicionales",
  //     "Control de pagos y fechas de vencimiento",
  //     "Notificaciones automáticas por correo electrónico",
  //     "Dashboard con métricas clave",
  //   ],
  //   techStack: [
  //     "Next.js",
  //     "Node.js",
  //     "PostgreSQL",
  //     "Automatización de correos",
  //   ],
  //   gallery: [
  //     "/projects/kedevshome/gallery-1.png",
  //     "/projects/kedevshome/gallery-2.png",
  //     "/projects/kedevshome/gallery-3.png",
  //   ],
  //   mockups: [
  //     "/projects/kedevshome/mockup-1.png",
  //     "/projects/kedevshome/mockup-2.png",
  //     "/projects/kedevshome/mockup-3.png",
  //   ],
  //   cta: "Explorar Plataforma",
  // },
];
